<?php

return [
    'app_version' => "6.2",
    'webhook_version' => "1.0",
    'app_release_date' => '2024-01-31', // Change to match date at release app
    'switcher_version' => "4",
    'pricing_version' => 4,
    'app_name' => 'transcy',
    'app_uid' => 3828261,
    'cdn_not_found' => 'https://tc.cdnhub.co/not-found/',
    'paginate_limit' => 10,
    'affiliate_api' => env('APP_ENV') === 'production' ? env('AFFILIATE_API', 'https://affiliate.fireapps.io/api/') : 'http://aff-dev.fireapps.io/api/',
    'metrics_api' => env('METRICS_API', 'https://metrics.fireapps.io'),
    'cdn_url' => env('CDN_URL'),
    'shopify_api_key' => env('SHOPIFY_API_KEY'),
    'INTERNAL_JWT' => env('INTERNAL_JWT', 'Basic b3ByX3Byb2R1Y3Rpb246UHNAaExHVDk='),
    'shopify_api_secret' => env('SHOPIFY_API_SECRET'),
    'front_url' => env('FRONT_URL'),
    'app_url_root_transcy_api' => env('APP_URL_ROOT_TRANSCY_API'),
    'firegroup_webhook_url' => env('FIREGROUP_WEBHOOK_URL', 'https://wh.transcy.io'),
    'firegroup_product_webhook_url' => env('FIREGROUP_WEBHOOK_PRODUCT_URL', 'https://pwh.transcy.io'),
    'app_key' => env('APP_KEY_ROOT'),
    'app_url' => env('APP_URL'),
    'cache_driver' => env('CACHE_DRIVER'),
    'fixer_io_key' => env('FIXER_IO_KEY'),
    'sync_second_sleep' => 5,
    'google_account' => env('APP_ENV') === 'production' ? 'google-service-account-credentials.json' : 'google-service-account-credentials-develop.json',
    'stores_block' => [],
    'stores_not_redirect' => [
        'undgretel.myshopify.com',
        'sitre.myshopify.com',
        'xie-xie-tea-taipei.myshopify.com',
        'sanepadel.myshopify.com',
        'trayus-by-c-c-design.myshopify.com',
        'nikopouches-dk.myshopify.com',
        'slamcosmetics.myshopify.com',
        'identshop.myshopify.com',
        'valor-cosmetics.myshopify.com',
        'mynidore.myshopify.com',
        'shop-unravvel.myshopify.com',
        'rafi-gr.myshopify.com'
    ],
    'store_metafield' => [55089135765, 5871960179],
    'review_url' => 'https://reviews.fireapps.io/api',
    'review_authorization' => 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5MDhiMGYyZi05N2Q0LTQ0NmItYWRkYS0zNDI0Y2NlNDIyNTQiLCJqdGkiOiJmMzQzMWIyOWExNTkyNmU3YmNiZjgxZWY1YmNhODE1ZWVhNDkxMzJjMGEwMmFlZDQwMjljODYwMGQ5MThjNmI0NGMwZTA0NTRlZDY0MThhYSIsImlhdCI6MTYxMjE3MzY0NiwibmJmIjoxNjEyMTczNjQ2LCJleHAiOjE5Mjc3MDY0NDYsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.xvAg-Z70giecWVe0daPIjxDarv0UJqI8uxLbsT0eYk_HvyNXVy_So_WGYwUiKd3oZbLLkN9hR5hoaCDKR_21gHuy5ol2RVE7NoH73zYE-9PCQWvTtUWwNItKGzpSvgcK0yKmN8kyYE3vRNWS2-UTrS4lrh955L-GP0_usskHF5JGj-uvJ96icqtyf9oLAc_Hl46DqPDMluvSk52kRGDXHIuAhsZBI1vSPeWwXsQk0uKrTU8rsBmvfUEPC52gBvRoEVpmQZyKYk1q8XCohnG5tCCK9XJY7fvcqb-bUCPFBpSQsMhBnNFJteXgMCoLbMb8pvWNYAUsmRWPC3qIyfpOm-srbKNvwwHiM9l20JwJbx-9HLPV-vNoIYFE4PV5VccwlieFaPwC7Xg5X6bZ_4vEiWlp3BzMqBHxy87j1KBuWcXk7-N7Sqcyt9JY05JEGFcLfuINv0Ii0vpzc-_LTCfOQXr8dlI3nk-oQbfmvTVBmDDbrmntYzcyYLGF9NOc1P59WGAr1iGtTwzxLR5-uqcnyTdWwehHWo6AhigQXNDOLy5gRwiLm-k9Kox35ToeW2soUXeMLq8V38QeZjrqI6UK8GWzP8GepWRVaX1dn1MWDG3-xsWkvw7TTOR08VNlgbGCL8akkUsii_2MuOjI818T3FORGA--AOK1ezSYOWaHM_k',
    'proxy1' => env('PROXY_LEVEL1', 'http://transcyproxylv3:ivLBIPGfzWbboaggcvp2@proxy-lv3.transcy.io:8080'),
    'proxy2' => env('PROXY_LEVEL2', 'http://transcyproxylv1:ivLBIPGfzWbboaggcvp2@proxy-lv1.transcy.io:8080'),
    'proxy3' => env('PROXY_LEVEL3', 'http://transcyproxylv2:ivLBIPGfzWbboaggcvp2@proxy-lv2.transcy.io:8080'),
    'limit_translate' => 4000,
    'apply_product_translation_status' => true,
    'ignore_option' => 'Title',
    'ignore_variant' => 'Default Title',
    'stores_show_free_plan' => [
        'souvie-brazilian-concept-store.myshopify.com',
        'nhi-transcy-4.myshopify.com',
        'utoper.myshopify.com',
    ],
    'embedded' => [
        'name' => ENV('EMBEDDED_APP_NAME')
    ],
    'limit_store_v4' => 1000000, //ENV('LIMIT_STORE_V4', 1000),
    'segment_write_key' => env('SEGMENT_KEY', '9EXwPL2mhoOEC7JdVvcsjV6oE0tDmaHA'),
    'date_force_new_pricing' => env('DATE_FORCE_NEW_PRICING', '2023-06-01'),
    'index_limit_rows' => 2000,
    'use_wp_translate_service' => env('USE_WP_TRANSLATE_SERVICE', false),
    'language_prioritize' => [
        'en' => 'English',
        'de' => 'German',
        'fr' => 'French',
        'es' => 'Spanish',
        'it' => 'Italian',
        'nl' => 'Dutch',
        'sv' => 'Swedish',
        'no' => 'Norwegian',
    ]
];
