<?php

return [
    'view_choose_plan' => 'View Choose plan',
    'choose_plan' => 'Choose plan',
    'choose_plan_with_extend_limit' => 'Choose plan with extend limit',
    'plan_updates' => 'Plan updates',
    'reinstall' => 'Re-install',
    'uninstall' => 'App uninstall',
    'expert_ticket' => 'Experts service draft ticket',
    'buymore' => 'Store limit information',
    'upgrade_action' => 'Change plan: position tracking',
    'upgrade_trackings' => [
        'metric' => 'Metric_Can\'t switch to advanced language',
        'language_limit' => 'Language_You\'ve hit your plan limit',
        'language_cant_publish' => 'Language_Can\'t publish language(s)',
        'language_unable_publish' => 'Language_Unable to publish language',
        'language_upgrade_plan' => 'Language_Upgrade your plan to use this feature',
        'language_cant_disable' => 'Language_Can\'t disable third-party app translations',
        'language_cant_switch' => 'Language_Can\'t switch to advanced language',
        'language_add' => 'Language_Add Language',
        'translation_limit' => 'Manage translation_You\'ve hit the translation limit of %d products.',
        'translation_only_prod' => 'Manage translation_Only %d products can be translated',
        'translation_banner' => 'Manage translation_Banner limit function',
        'replace_image_unable_active' => 'Replace image_Unable to activate_Replace image',
        'replace_image_limit' => 'Replace image_Action exceeds the limit by %d pages_Replace image',
        'replace_image_upgrade' => 'Replace image_Upgrade to access advanced features_Replace image',
        'replace_image_banner' => 'Replace image_Banner limit function',
        'auto_translate_unable_active' => 'Auto translate_Unable to activate_Auto translate',
        'auto_translate_limit' => 'Auto translate_Action exceeds the limit by %d pages_Auto translate',
        'auto_translate_upgrade' => 'Auto translate_Upgrade to access advanced features_Auto translate',
        'auto_translate_banner' => 'Auto translate_Banner limit function',
        'glossary_unable_active' => 'Glossary_Unable to activate',
        'glossary_limit' => 'Glossary_You\'ve hit your plan limit of %d rules',
        'currency_limit' => 'Currency_You\'ve hit your plan limit',
        'currency_unable_publish' => 'Currency_Unable to publish',
    ]
];
